//GOAL OF THIS FUNCTION IS TO CATCH ASYNCHRONOUS ERROR.ASYNC FUNCTION RETURN PROMISES SO WE CATCH IF THE PROMISE GET
//REJECTED..
//LECTURE 115
module.exports = (fn) => (req, res, next) => {
  fn(req, res, next).catch((err) => {
    next(err);
  });
};
//WHY RETURN IS REQUIRED ? AS WHEN CATCHASYNC IS CALLED IT THEN INSTANTLY CALLS THE FN WHICH WE DO NOT WANT . WE WANT IT
//CALLED ONLY WHEN GETALLTOURS PATH IS TRIGERRED.IT SHOULD WAIT UNTIL EXPRESS CALLS IT.
